/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StudentApplication;

import java.util.ArrayList;
import java.util.Scanner;

public class StudentApplication {
    public static void main(String[] args) {
        ArrayList<Student> students = new ArrayList<>();
        try (Scanner scanner = new Scanner(System.in)) {
            int choice;
            
            do {
                System.out.println("Student Management Application Menu:");
                System.out.println("1. Capture a new student");
                System.out.println("2. Search for a student");
                System.out.println("3. Delete a student");
                System.out.println("4. View student report");
                System.out.println("5. Exit");
                
                System.out.print("Enter your choice: ");
                choice = scanner.nextInt();
                
                switch (choice) {
                    case 1 -> // Capture a new student
                        captureStudent(scanner, students);
                    case 2 -> // Search for a student
                        searchStudent(scanner, students);
                    case 3 -> // Delete a student
                        deleteStudent(scanner, students);
                    case 4 -> // View student report
                        Student.studentReport(students);
                    case 5 -> // Exit the application
                        System.out.println("Exiting the application.");
                    default -> System.out.println("Invalid choice. Please enter a valid option.");
                }
            } while (choice != 5);
        }
    }

    public class StudentImpl extends Student {

        /**
         *
         * @param id
         * @param name
         * @param age
         * @param email
         * @param course
         */
        public StudentImpl(int id, String name, int age, String email, String course) {
        super(id, name, age, email, course);
    }
    
}
    private static void captureStudent(Scanner scanner, ArrayList<Student> students) {       
      
   
    }

    private static void searchStudent(Scanner scanner, ArrayList<Student> students) {
        
    }

    private static void deleteStudent(Scanner scanner, ArrayList<Student> students) {
        
    }
}
